import { colors } from "@/theme/colors";
import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  header: {
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: colors.primaryText, fontSize: 16, fontWeight: "800" },
  muted: { color: colors.secondaryText, fontSize: 13, fontWeight: "700" },
  name: { flex: 1, color: colors.primaryText, fontSize: 18, fontWeight: "900" },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
    gap: 16,
  },
  emptyIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  emptyTitle: {
    color: colors.primaryText,
    fontSize: 24,
    fontWeight: "900",
    textAlign: "center",
  },
  emptyBody: {
    color: colors.secondaryText,
    fontSize: 16,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 8,
  },
  emptyHint: {
    color: colors.secondaryText,
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
  },
  categoryRow: { flexDirection: "row", gap: 12 },
  categoryCard: { flex: 1, padding: 14, gap: 10, width: 140 },
  categoryNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  categoryIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryName: {
    flex: 1,
    color: colors.primaryText,
    fontSize: 13,
    fontWeight: "800",
  },
  categoryAmount: {
    color: colors.primaryText,
    fontSize: 17,
    fontWeight: "900",
  },
  actions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 6,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { color: colors.primaryText, fontSize: 18, fontWeight: "900" },
  viewAllBtn: { flexDirection: "row", alignItems: "center", gap: 2 },
  viewAllText: { color: colors.violet, fontSize: 14, fontWeight: "700" },
  budgetIncomeRow: { flexDirection: "row", gap: 12, marginBottom: 24 },
  budgetIncomeCard: { flex: 1, padding: 16, gap: 8, alignItems: "center" },
  biIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  biLabel: {
    color: colors.secondaryText,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  biAmount: { fontSize: 24, fontWeight: "900" },
  biSubtext: { color: colors.secondaryText, fontSize: 11, fontWeight: "700" },
  expensesCard: { overflow: "hidden" },
});
