import { colors } from "@/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.card,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  sheet: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    gap: 16,
    paddingBottom: 40,
  },
  handle: {
    alignSelf: "center",
    width: 48,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { color: colors.primaryText, fontSize: 22, fontWeight: "900" },
  close: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.cardSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  amountWrap: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  currency: { color: colors.secondaryText, fontSize: 34, fontWeight: "800" },
  amount: {
    color: colors.primaryText,
    fontSize: 56,
    fontWeight: "900",
    minWidth: 150,
    textAlign: "center",
  },
  dateInfo: {
    alignSelf: "center",
    color: colors.secondaryText,
    fontSize: 14,
    fontWeight: "700",
    marginTop: -8,
  },
  ai: {
    alignSelf: "center",
    color: colors.violet,
    borderColor: "rgba(139,92,246,0.35)",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    overflow: "hidden",
    fontWeight: "800",
  },
  field: {
    height: 54,
    borderRadius: 18,
    borderColor: colors.border,
    borderWidth: 1,
    backgroundColor: colors.cardSoft,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
  },
  input: { flex: 1, color: colors.primaryText, fontSize: 15 },
  toggleContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toggle: {
    height: 54,
    borderRadius: 18,
    borderColor: colors.border,
    borderWidth: 1,
    backgroundColor: colors.cardSoft,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  toggleText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
  error: { color: colors.coral, fontWeight: "800" },
  voice: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  voiceText: { color: colors.secondaryText, fontWeight: "800" },
});
