import { StyleSheet } from "react-native";

import { colors } from "@/theme/colors";

export const screenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  tabs: {
    flexDirection: "row",
    marginHorizontal: 10,
    marginVertical: 16,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 4,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
  },
  tabActive: { backgroundColor: colors.cardSoft },
  tabText: { color: colors.secondaryText, fontSize: 14, fontWeight: "800" },
  tabTextActive: { color: colors.primaryText },
  scroll: { paddingHorizontal: 10 },
  overviewCard: { padding: 20, marginBottom: 24 },
  overviewRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  overviewItem: { alignItems: "center", gap: 8 },
  overviewDivider: { width: 1, height: 40, backgroundColor: colors.border },
  overviewLabel: {
    color: colors.secondaryText,
    fontSize: 13,
    fontWeight: "700",
  },
  overviewAmount: {
    color: colors.primaryText,
    fontSize: 24,
    fontWeight: "900",
  },
  incomeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  incomeIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  section: { gap: 12 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  sectionTitle: { color: colors.primaryText, fontSize: 20, fontWeight: "900" },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.cardSoft,
    borderWidth: 1,
    borderColor: colors.border,
  },
  addBtnText: { color: colors.violet, fontSize: 14, fontWeight: "800" },
  emptyCard: { padding: 32, alignItems: "center", gap: 12 },
  emptyTitle: { color: colors.primaryText, fontSize: 20, fontWeight: "800" },
  emptyBody: {
    color: colors.secondaryText,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  budgetCard: { padding: 16, gap: 12 },
  budgetHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  budgetIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  budgetMeta: { flex: 1, gap: 4 },
  budgetName: { color: colors.primaryText, fontSize: 16, fontWeight: "800" },
  budgetSubtext: { color: colors.secondaryText, fontSize: 13 },
  budgetRight: { alignItems: "flex-end", gap: 2 },
  budgetPercentage: {
    color: colors.primaryText,
    fontSize: 18,
    fontWeight: "900",
  },
  budgetRemaining: { fontSize: 12, fontWeight: "700" },
  progressBar: {
    height: 6,
    backgroundColor: colors.cardSoft,
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 3 },
  incomeCard: { padding: 14 },
  incomeRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  incomeIconSmall: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  incomeMeta: { flex: 1, gap: 2 },
  incomeName: { color: colors.primaryText, fontSize: 15, fontWeight: "700" },
  incomeDate: { color: colors.secondaryText, fontSize: 12 },
  incomeAmount: { fontSize: 16, fontWeight: "800" },
});

export const modalStyles = StyleSheet.create({
  overlay: { flex: 1 },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modal: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    borderTopWidth: 1,
    borderColor: colors.border,
    gap: 16,
    minHeight: "70%",
    maxHeight: "85%",
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignSelf: "center",
    marginBottom: 8,
  },
  modalTitle: {
    color: colors.primaryText,
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  amountWrap: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  currency: { color: colors.mint, fontSize: 34, fontWeight: "800" },
  amountInput: {
    color: colors.primaryText,
    fontSize: 56,
    fontWeight: "900",
    minWidth: 150,
    textAlign: "center",
  },
  label: {
    color: colors.secondaryText,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    marginTop: 8,
  },
  categories: { flexDirection: "row", gap: 12, paddingVertical: 8 },
  category: { alignItems: "center", gap: 6, width: 68 },
  categoryIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryName: {
    color: colors.secondaryText,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  field: {
    height: 54,
    borderRadius: 18,
    borderColor: colors.border,
    borderWidth: 1,
    backgroundColor: colors.cardSoft,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  input: { color: colors.primaryText, fontSize: 15 },
  cancel: {
    color: colors.secondaryText,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    paddingVertical: 12,
  },
});
