import { colors } from "@/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerTop: {
    paddingTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { color: colors.primaryText, fontSize: 34, fontWeight: "900" },
  center: { alignItems: "center", gap: 10, paddingTop: 8, marginBottom: 20 },
  segment: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.03)",
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    padding: 4,
  },
  segmentText: {
    color: colors.secondaryText,
    fontSize: 13,
    fontWeight: "800",
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  segmentTextActive: { color: colors.primaryText },
  segmentActiveWrap: { backgroundColor: colors.primaryText, borderRadius: 999 },
  segmentActive: { color: colors.bg },
  monthSelector: { flexDirection: "row", alignItems: "center", gap: 12 },
  navArrow: {
    color: colors.primaryText,
    fontSize: 24,
    fontWeight: "700",
    paddingHorizontal: 8,
  },
  month: {
    color: colors.secondaryText,
    fontWeight: "800",
    fontSize: 14,
    minWidth: 120,
    textAlign: "center",
  },
  total: {
    color: colors.primaryText,
    fontSize: 48,
    fontWeight: "900",
    letterSpacing: -1,
  },
  badgeWrap: { flexDirection: "row", alignItems: "center" },
  badge: { fontSize: 14, fontWeight: "800" },
  prediction: {
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  muted: { color: colors.secondaryText, fontSize: 13, fontWeight: "700" },
  predicted: {
    color: colors.primaryText,
    fontSize: 24,
    fontWeight: "900",
    marginTop: 4,
  },
  right: { alignItems: "flex-end" },
  warning: {
    color: colors.amber,
    fontSize: 14,
    fontWeight: "800",
    marginTop: 4,
  },
  sectionTitle: {
    color: colors.primaryText,
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 12,
  },
  breakdown: { padding: 16 },
  noData: {
    color: colors.secondaryText,
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 20,
  },
  categoryDetails: {
    padding: 18,
    gap: 14,
    marginTop: 12,
  },
  categoryDetailsTitle: {
    color: colors.primaryText,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
  },
  categoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  categoryLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  categoryIconSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  categoryName: {
    color: colors.primaryText,
    fontSize: 14,
    fontWeight: "700",
  },
  categoryRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  categoryAmount: {
    color: colors.primaryText,
    fontSize: 15,
    fontWeight: "800",
  },
  categoryPercent: {
    color: colors.secondaryText,
    fontSize: 12,
    fontWeight: "600",
  },
});
